### ISSUE TITLE
Manage docker login

### ISSUE THREAD

**Issue by pjean** [leighmcculloch/vagrant-docker-compose#27]
In order to pull image from private registry, we need to be authenticated.
login command : https://docs.docker.com/engine/reference/commandline/login/
Could  you please provide the capability to have an interactive login during the provisioning ?

**Comment by leighmcculloch** [comment]
During provisioning in vagrant it's not possible to interact with the prompt (I think), so you'd need to place the username and password into the login command. I'm not sure yet if it makes sense to make this a configuration option for `vagrant-docker-compose` because it isn't a configuration for `docker-compose` but rather for `docker` itself. Maybe it should be added to the built-in `docker` provisioner.

Lets see if we can get you going, and then decide where the feature should live. Does the below achieve what you want? You'd need to add it after provisioning `docker` and before provisioning `docker-compose`.

```ruby
  config.vm.provision :shell, inline: "docker login -u #{ENV['DOCKER_USERNAME']} -p #{ENV['DOCKER_PASSWORD']} server"
```

Example:
```ruby
  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :docker
  config.vm.provision :shell, inline: "docker login -u #{ENV['DOCKER_USERNAME']} -p #{ENV['DOCKER_PASSWORD']} server"
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always"
```

**Comment by leighmcculloch** [comment]
I have an elegant solution on it's way, if you can confirm the above works.

**Comment by pjean** [comment]
I thought the same thing but I receive 401 http error when I used inline shell provision for login. 
vagrant-hostsupdater plugin interact with the prompt in order to modify the hosts file as root user.

**Comment by leighmcculloch** [comment]
https://github.com/leighmcculloch/vagrant-docker-login works for me and can login me in. Can you give it a go and let me know if you still get the 401 http error? Considering vagrant provisioning is largely meant to be automatic I'd like to see if we can get the command line option working, otherwise I'll look further into the how vagrant-hostsupdater does its prompts.

**Comment by leighmcculloch** [comment]
Please reopen if the above doesn't solve your need.
