### ISSUE TITLE
Redirect docker-compose logs to vagrant stdout

### ISSUE THREAD

**Issue by wstewarttennes** [leighmcculloch/vagrant-docker-compose#61]
Haven't been able to figure this one out. When using docker-compose normally, an 'up' command shows the logs of each container running -- would love for the same thing to happen when using vagrant up here. 

FYI This can be accomplished by running `vagrant ssh -c "docker-compose logs -f"`, but I think it'd be a nice feature to replicate this like the `docker-compose up` command does natively.

**Comment by leighmcculloch** [comment]
By default the `up` command is executed with the `-d` option which means you don't get the logs. You can change this by setting the `command_options` parameter. See the config details here: https://github.com/leighmcculloch/vagrant-docker-compose#other-configs

I'll close the issue because this should solve your issue but please reopen if needed.
